<a href="https://colab.research.google.com/github/abyanrizz/practicallinearalgebra/blob/main/Chapter_5_.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#chapter 5

A matrix is a vector taken to the next level. Matrices are highly versatile mathematical
objects. They can store sets of equations, geometric transformations, the positions
of particles over time, financial records, and myriad other things. In data science,
matrices are sometimes called data tables, in which rows correspond to observations
(e.g., customers) and columns correspond to features (e.g., purchases).
This and the following two chapters will take your knowledge about linear algebra to
the next level. Get a cup of coffee and put on your thinking cap. Your brain will be
bigger by the end of the chapter.
Creating and Visualizing Matrices in NumPy
Depending on the context, matrices can be conceptualized as a set of column vectors
stacked next to each other (e.g., a data table of observations-by-features), as a set of
row vectors layered on top of each other (e.g., multisensor data in which each row is a
time series from a different channel), or as an ordered collection of individual matrix
elements (e.g., an image in which each matrix element encodes pixel intensity value).
Visualizing, Indexing, and Slicing Matrices
Small matrices can simply be printed out in full, like the following examples:
1 2
π 4
6 7
,
−6 1/3
e
4.3 −1.4
6/5 0

But that’s not scalable, and matrices that you work with in practice can be large,
perhaps containing billions of elements. Therefore, larger matrices can be visualized
61

as images. The numerical value of each element of the matrix maps onto a color
in the image. In most cases, the maps are pseudo-colored because the mapping of
numerical value onto color is arbitrary. Figure 5-1 shows some examples of matrices
visualized as images using the Python library matplotlib.

Figure 5-1. Three matrices, visualized as images
Matrices are indicated using bold-faced capital letters, like matrix A or M. The size
of a matrix is indicated using (row, column) convention. For example, the following
matrix is 3 × 5 because it has three rows and five columns:
1 3 5 7 9
0 2 4 6 8
1 4 7 8 9
You can refer to specific elements of a matrix by indexing the row and column posi‐
tion: the element in the 3rd row and 4th column of matrix A is indicated as a3, 4 (and
in the previous example matrix, a3, 4 = 8). Important reminder: math uses 1-based
indexing whereas Python uses 0-based indexing. Thus, element a3, 4 is indexed in
Python as A[2,3].
Extracting a subset of rows or columns of a matrix is done through slicing. If you
are new to Python, you can consult Chapter 16 for an introduction to slicing lists
and NumPy arrays. To extract a section out of a matrix, you specify the start and
end rows and columns, and that the slicing goes in steps of 1. The online code walks
you through the procedure, and the following code shows an example of extracting a
submatrix from rows 2–4 and columns 1–5 of a larger matrix:

In [ ]:
A = np.arange(60).reshape(6,10)
sub = A[1:4:1,0:5:1]

In [7]:
Original matrix:
[[ 0 1 2 3 4 5 6 7 8 9]
[10 11 12 13 14 15 16 17 18 19]
[20 21 22 23 24 25 26 27 28 29]

SyntaxError: invalid syntax (2099835956.py, line 1)

In [ ]:
[30 31 32 33 34 35 36 37 38 39]
[40 41 42 43 44 45 46 47 48 49]
[50 51 52 53 54 55 56 57 58 59]]
Submatrix:
[[10 11 12 13 14]
[20 21 22 23 24]
[30 31 32 33 34]]

Special Matrices
There is an infinite number of matrices, because there is an infinite number of ways
of organizing numbers into a matrix. But matrices can be described using a relatively
small number of characteristics, which creates “families” or categories of matrices.
These categories are important to know, because they appear in certain operations or
have certain useful properties.
Some categories of matrices are used so frequently that they have dedicated NumPy
functions to create them. Following is a list of some common special matrices and
Python code to create them;1

you can see what they look like in Figure 5-2:

Random numbers matrix
This is a matrix that contains numbers drawn at random from some distribu‐
tion, typically Gaussian (a.k.a. normal). Random-numbers matrices are great for
exploring linear algebra in code, because they are quickly and easily created with
any size and rank (matrix rank is a concept you’ll learn about in Chapter 16).
There are several ways to create random matrices in NumPy, depending on
which distribution you want to draw numbers from. In this book, we’ll mostly
use Gaussian-distributed numbers:

In [ ]:
Mrows = 4 # shape 0
Ncols = 6 # shape 1
A = np.random.randn(Mrows,Ncols)

Square versus nonsquare
A square matrix has the same number of rows as columns; in other words, the
matrix is in R

N × N
. A nonsquare matrix, also sometimes called a rectangular
matrix, has a different number of rows and columns. You can create square and
rectangular matrices from random numbers by adjusting the shape parameters in
the previous code.
Rectangular matrices are called tall if they have more rows than columns and
wide if they have more columns than rows.

Creating and Visualizing Matrices in NumPy | 63

Diagonal
The diagonal of a matrix is the elements starting at the top-left and going down
to the bottom-right. A diagonal matrix has zeros on all the off-diagonal elements;
the diagonal elements may also contain zeros, but they are the only elements that
may contain nonzero values.
The NumPy function np.diag() has two behaviors depending on the inputs:
input a matrix and np.diag will return the diagonal elements as a vector; input
a vector and np.diag will return a matrix with those vector elements on the
diagonal. (Note: extracting the diagonal elements of a matrix is not called “diago‐
nalizing a matrix”; that is a separate operation introduced in Chapter 13.)
Triangular
A triangular matrix contains all zeros either above or below the main diagonal.
The matrix is called upper triangular if the nonzero elements are above the
diagonal and lower triangular if the nonzero elements are below the diagonal.
NumPy has dedicated functions to extract the upper (np.triu()) or lower
(np.tril()) triangle of a matrix.
Identity
The identity matrix is one of the most important special matrices. It is the equiva‐
lent of the number 1, in that any matrix or vector times the identity matrix is that
same matrix or vector. The identity matrix is a square diagonal matrix with all
diagonal elements having a value of 1. It is indicated using the letter I. You might
see a subscript to indicate its size (e.g., I5 is the 5 × 5 identity matrix); if not, then
you can infer the size from context (e.g., to make the equation consistent).
You can create an identity matrix in Python using np.eye().
Zeros
The zeros matrix is comparable to the zeros vector: it is the matrix of all zeros.
Like the zeros vector, it is indicated using a bold-faced zero: 0. It can be a bit
confusing to have the same symbol indicate both a vector and a matrix, but this
kind of overloading is common in math and science notation.
The zeros matrix is created using the np.zeros() function.